name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      # - name: Run tests
      #   run: npm run test
        
      - name: Publish packages
        uses: decentraland/oddish-action@master
        id: publish_package
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true
          # provenance: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}